name: Build Templates
on: [push, pull_request, workflow_dispatch]

jobs:
  build:
    strategy:
      matrix:
        os: [windows-latest, ubuntu-latest]
    runs-on: ${{ matrix.os }}
    permissions:
      contents: write
    env:
      PYTHONUTF8: ${{ matrix.os == 'windows-latest' && '1' || '' }}
    steps:
      - uses: actions/checkout@v4
      - name: Checkout Haixing-Hu/latex-chinese-fonts
        uses: actions/checkout@v4
        with:
          repository: Haixing-Hu/latex-chinese-fonts
          path: fonts
      - uses: typst-community/setup-typst@v4
      - run: typst fonts --font-path fonts
      - run: python3 ci/mode_switch.py dev templates
      - run: python3 ci/build.py
      - uses: actions/upload-artifact@v4
        with:
          name: templates-build-${{ github.run_id }}-${{ matrix.os }}
          path: build/*.pdf
      - name: Configure Git
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
      - name: Deploy PDF files to build branch
        if: matrix.os == 'windows-latest'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GIT_TERMINAL_PROMPT: 0
        run: |
          python3 ci/deploy.py